[build.environment]
  YARN_VERSION = "1.12.1"
  NPM_VERSION = "6.4.1"

[build]
  command = "yarn build"
  publish = "dist"

[context.production.environment]
  HUGO_VERSION = "0.80.0"
  HUGO_ENV = "production"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.80.0"

[context.deploy-preview]
  command = "yarn build:preview"
